FROM golang:1.25.2-alpine3.22 AS build
RUN apk add -U make binutils
WORKDIR /build
RUN --mount=type=bind,source=.,destination=/build,rw \
    make binary-build && \
    mv community /usr/bin/community

FROM alpine:3.22.1
WORKDIR /application
COPY --from=build /usr/bin/community /application/community
ENTRYPOINT [ "/application/community", "server" ]
