fqdn: "api.stormhead.org"

image: "latest"

postgres:
  host: "postgres.postgres.svc.cluster.local"
  port: 5432
  user: "postgres"
  password: ""
  database: "community"

kafka:
  host: kafka-broker.kafka.svc.cluster.local
  port: 9092
