// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.1
// source: community.proto

package proto

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Community message
type Community struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OwnerId       string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Slug          string                 `protobuf:"bytes,5,opt,name=slug,proto3" json:"slug,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Community) Reset() {
	*x = Community{}
	mi := &file_community_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Community) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Community) ProtoMessage() {}

func (x *Community) ProtoReflect() protoreflect.Message {
	mi := &file_community_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Community.ProtoReflect.Descriptor instead.
func (*Community) Descriptor() ([]byte, []int) {
	return file_community_proto_rawDescGZIP(), []int{0}
}

func (x *Community) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Community) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *Community) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Community) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Community) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Community) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Community) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Create Community
type CreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       string                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Slug          string                 `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_community_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_community_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_community_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *CreateRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *CreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	mi := &file_community_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_community_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_community_proto_rawDescGZIP(), []int{2}
}

func (x *CreateResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Get Community
type GetCommunityRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Identifier:
	//
	//	*GetCommunityRequest_Id
	//	*GetCommunityRequest_Slug
	Identifier    isGetCommunityRequest_Identifier `protobuf_oneof:"identifier"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommunityRequest) Reset() {
	*x = GetCommunityRequest{}
	mi := &file_community_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommunityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommunityRequest) ProtoMessage() {}

func (x *GetCommunityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_community_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommunityRequest.ProtoReflect.Descriptor instead.
func (*GetCommunityRequest) Descriptor() ([]byte, []int) {
	return file_community_proto_rawDescGZIP(), []int{3}
}

func (x *GetCommunityRequest) GetIdentifier() isGetCommunityRequest_Identifier {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *GetCommunityRequest) GetId() string {
	if x != nil {
		if x, ok := x.Identifier.(*GetCommunityRequest_Id); ok {
			return x.Id
		}
	}
	return ""
}

func (x *GetCommunityRequest) GetSlug() string {
	if x != nil {
		if x, ok := x.Identifier.(*GetCommunityRequest_Slug); ok {
			return x.Slug
		}
	}
	return ""
}

type isGetCommunityRequest_Identifier interface {
	isGetCommunityRequest_Identifier()
}

type GetCommunityRequest_Id struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3,oneof"`
}

type GetCommunityRequest_Slug struct {
	Slug string `protobuf:"bytes,2,opt,name=slug,proto3,oneof"`
}

func (*GetCommunityRequest_Id) isGetCommunityRequest_Identifier() {}

func (*GetCommunityRequest_Slug) isGetCommunityRequest_Identifier() {}

type GetCommunityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Community     *Community             `protobuf:"bytes,1,opt,name=community,proto3" json:"community,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommunityResponse) Reset() {
	*x = GetCommunityResponse{}
	mi := &file_community_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommunityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommunityResponse) ProtoMessage() {}

func (x *GetCommunityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_community_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommunityResponse.ProtoReflect.Descriptor instead.
func (*GetCommunityResponse) Descriptor() ([]byte, []int) {
	return file_community_proto_rawDescGZIP(), []int{4}
}

func (x *GetCommunityResponse) GetCommunity() *Community {
	if x != nil {
		return x.Community
	}
	return nil
}

// List Communities
type ListCommunitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`  // По умолчанию 40
	Cursor        string                 `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"` // ID последнего элемента предыдущей страницы
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCommunitiesRequest) Reset() {
	*x = ListCommunitiesRequest{}
	mi := &file_community_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCommunitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommunitiesRequest) ProtoMessage() {}

func (x *ListCommunitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_community_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommunitiesRequest.ProtoReflect.Descriptor instead.
func (*ListCommunitiesRequest) Descriptor() ([]byte, []int) {
	return file_community_proto_rawDescGZIP(), []int{5}
}

func (x *ListCommunitiesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListCommunitiesRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type ListCommunitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Communities   []*Community           `protobuf:"bytes,1,rep,name=communities,proto3" json:"communities,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"` // ID для следующей страницы
	HasMore       bool                   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`         // Есть ли ещё элементы
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCommunitiesResponse) Reset() {
	*x = ListCommunitiesResponse{}
	mi := &file_community_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCommunitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommunitiesResponse) ProtoMessage() {}

func (x *ListCommunitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_community_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommunitiesResponse.ProtoReflect.Descriptor instead.
func (*ListCommunitiesResponse) Descriptor() ([]byte, []int) {
	return file_community_proto_rawDescGZIP(), []int{6}
}

func (x *ListCommunitiesResponse) GetCommunities() []*Community {
	if x != nil {
		return x.Communities
	}
	return nil
}

func (x *ListCommunitiesResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

func (x *ListCommunitiesResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

var File_community_proto protoreflect.FileDescriptor

const file_community_proto_rawDesc = "" +
	"\n" +
	"\x0fcommunity.proto\x12\x05proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/api/annotations.proto\"\xf6\x01\n" +
	"\tCommunity\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x12\n" +
	"\x04slug\x18\x05 \x01(\tR\x04slug\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"t\n" +
	"\rCreateRequest\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\tR\aownerId\x12\x12\n" +
	"\x04slug\x18\x02 \x01(\tR\x04slug\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\" \n" +
	"\x0eCreateResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"K\n" +
	"\x13GetCommunityRequest\x12\x10\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x12\x14\n" +
	"\x04slug\x18\x02 \x01(\tH\x00R\x04slugB\f\n" +
	"\n" +
	"identifier\"F\n" +
	"\x14GetCommunityResponse\x12.\n" +
	"\tcommunity\x18\x01 \x01(\v2\x10.proto.CommunityR\tcommunity\"F\n" +
	"\x16ListCommunitiesRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\tR\x06cursor\"\x89\x01\n" +
	"\x17ListCommunitiesResponse\x122\n" +
	"\vcommunities\x18\x01 \x03(\v2\x10.proto.CommunityR\vcommunities\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore2\xca\x02\n" +
	"\x10CommunityService\x12N\n" +
	"\x06Create\x12\x14.proto.CreateRequest\x1a\x15.proto.CreateResponse\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/communities\x12~\n" +
	"\fGetCommunity\x12\x1a.proto.GetCommunityRequest\x1a\x1b.proto.GetCommunityResponse\"5\x82\xd3\xe4\x93\x02/Z\x1a\x12\x18/communities/slug/{slug}\x12\x11/communities/{id}\x12f\n" +
	"\x0fListCommunities\x12\x1d.proto.ListCommunitiesRequest\x1a\x1e.proto.ListCommunitiesResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/communitiesB\bZ\x06/protob\x06proto3"

var (
	file_community_proto_rawDescOnce sync.Once
	file_community_proto_rawDescData []byte
)

func file_community_proto_rawDescGZIP() []byte {
	file_community_proto_rawDescOnce.Do(func() {
		file_community_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_community_proto_rawDesc), len(file_community_proto_rawDesc)))
	})
	return file_community_proto_rawDescData
}

var file_community_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_community_proto_goTypes = []any{
	(*Community)(nil),               // 0: proto.Community
	(*CreateRequest)(nil),           // 1: proto.CreateRequest
	(*CreateResponse)(nil),          // 2: proto.CreateResponse
	(*GetCommunityRequest)(nil),     // 3: proto.GetCommunityRequest
	(*GetCommunityResponse)(nil),    // 4: proto.GetCommunityResponse
	(*ListCommunitiesRequest)(nil),  // 5: proto.ListCommunitiesRequest
	(*ListCommunitiesResponse)(nil), // 6: proto.ListCommunitiesResponse
	(*timestamppb.Timestamp)(nil),   // 7: google.protobuf.Timestamp
}
var file_community_proto_depIdxs = []int32{
	7, // 0: proto.Community.created_at:type_name -> google.protobuf.Timestamp
	7, // 1: proto.Community.updated_at:type_name -> google.protobuf.Timestamp
	0, // 2: proto.GetCommunityResponse.community:type_name -> proto.Community
	0, // 3: proto.ListCommunitiesResponse.communities:type_name -> proto.Community
	1, // 4: proto.CommunityService.Create:input_type -> proto.CreateRequest
	3, // 5: proto.CommunityService.GetCommunity:input_type -> proto.GetCommunityRequest
	5, // 6: proto.CommunityService.ListCommunities:input_type -> proto.ListCommunitiesRequest
	2, // 7: proto.CommunityService.Create:output_type -> proto.CreateResponse
	4, // 8: proto.CommunityService.GetCommunity:output_type -> proto.GetCommunityResponse
	6, // 9: proto.CommunityService.ListCommunities:output_type -> proto.ListCommunitiesResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_community_proto_init() }
func file_community_proto_init() {
	if File_community_proto != nil {
		return
	}
	file_community_proto_msgTypes[3].OneofWrappers = []any{
		(*GetCommunityRequest_Id)(nil),
		(*GetCommunityRequest_Slug)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_community_proto_rawDesc), len(file_community_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_community_proto_goTypes,
		DependencyIndexes: file_community_proto_depIdxs,
		MessageInfos:      file_community_proto_msgTypes,
	}.Build()
	File_community_proto = out.File
	file_community_proto_goTypes = nil
	file_community_proto_depIdxs = nil
}
