apiVersion: v2
name: postgres
description: postgres
type: application
version: "0.1.0"
appVersion: "0.1.0"

dependencies:
  - name: postgres
    version: 0.1.0
    repository: file://../../../../infrastructure/postgres/chart
