apiVersion: apps/v1
kind: Deployment
metadata:
  name: mail
  labels:
    application: mail
spec:
  replicas: 1
  selector:
    matchLabels:
      application: mail
  template:
    metadata:
      labels:
        application: mail
    spec:
      containers:
        - name: mail
          image: stormic/backend:{{ $.Values.image }}
          imagePullPolicy: IfNotPresent
          command:
            - "backend"
          args:
            - "worker"
          env:
            - name: VERSION
              value: "0.1.0"

            - name: KAFKA_HOST
              value: "{{ $.Values.kafka.host }}"

            - name: KAFKA_PORT
              value: "{{ $.Values.kafka.port }}"

            - name: KAFKA_TOPIC
              value: "{{ $.Values.kafka.topic }}"

            - name: KAFKA_GROUP
              value: "{{ $.Values.kafka.group }}"

            - name: SMTP_HOST
              value: "{{ $.Values.smtp.host }}"

            - name: SMTP_PORT
              value: "{{ $.Values.smtp.port }}"

            - name: SMTP_USER
              value: "{{ $.Values.smtp.user }}"

            - name: SMTP_PASSWORD
              value: "{{ $.Values.smtp.password }}"

          resources:
            limits:
              cpu: "0.1"
              memory: "200Mi"
            requests:
              cpu: "0.1"
              memory: "200Mi"
