apiVersion: batch/v1
kind: Job
metadata:
  name: database-create
  labels:
    application: backend
spec:
  template:
    spec:
      containers:
        - name: migration
          image: stormic/backend:{{ $.Values.image }}
          command:
            - "psql"
          args:
            - "--host"
            - "{{ .Values.postgres.host }}"
            - "--port"
            - "{{ .Values.postgres.port }}"
            - "--user"
            - "{{ .Values.postgres.user }}"
            - "-w"
            - "-c"
            - "CREATE DATABASE {{ .Values.postgres.database }};"
      restartPolicy: Never
