FROM golang:1.25.2-alpine3.22 AS build
RUN apk add -U make binutils
WORKDIR /build
RUN --mount=type=bind,source=.,destination=/build,rw \
    make binary-build && \
    mv iam /usr/bin/iam

FROM alpine:3.22.1
WORKDIR /application
COPY --from=build /usr/bin/iam /application/iam
ENTRYPOINT [ "/application/iam", "server" ]
