apiVersion: batch/v1
kind: Job
metadata:
  name: database-migrate
  labels:
    application: community
spec:
  template:
    spec:
      containers:
        - name: migration
          image: gdemojkod/stormic-community-migration:{{ $.Values.image.migration }}
          command:
            - "atlas"
          args:
            - "migrate"
            - "apply"
            - "--dir"
            - "file:///migrations"
            - "--url"
            - "postgres://{{ .Values.postgres.user }}:{{ .Values.postgres.password }}@{{ .Values.postgres.host }}:{{ .Values.postgres.port }}/community?sslmode=disable"
      restartPolicy: Never
