apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: iam
  namespace: argocd
spec:
  project: default
  source:
    targetRevision: HEAD
    repoURL: https://github.com/stormhead-org/backend
    path: argocd/delivery/service/iam
    # helm:
    #   parameters:
    #     - name: "checker.fqdn"
    #       value: "stormhead.org"
  destination:
    namespace: iam
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
