name: iam
services:
  postgres:
    image: postgres:17.0-bookworm
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432

  kafka:
    image: apache/kafka:4.1.0
    ports:
      - 9092:9092

  s3:
    image: adobe/s3mock:4.9.1
    ports:
      - 9090:9090
      - 9191:9191
